In [ ]:
%%time
x = getFearDf('After_The_Rain',med2017fearFolder)
len(x)

In [1]:
x = getAudioDf('Big_Buck_Bunny')
f = getFearDf('Big_Buck_Bunny',med2017fearFolder)
t = getFearDf('Big_Buck_Bunny',med2017fearFolder)
f.Fear.unique()
f.tail()
x.tail()

NameError: name 'getAudioDf' is not defined

In [ ]:
X.shape,X_train.shape,X_test.shape
y.shape, y_train.shape, y_test.shape

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
est = GradientBoostingRegressor(n_estimators=2000,max_depth=1)
est.fit(X,y)

y_pred = est.predict(X)

# calculate accuracy
from sklearn import metrics
#print(metrics.accuracy_score(y, y_pred))

# IMPORTANT: first argument is true values, second argument is predicted values
#print(metrics.confusion_matrix(y, y_pred))

# calculate MAE using scikit-learn
from sklearn import metrics
print(metrics.mean_absolute_error(y, y_pred))

# calculate MSE using scikit-learn
print(metrics.mean_squared_error(y, y_pred))

# calculate RMSE using scikit-learn
print(np.sqrt(metrics.mean_squared_error(y, y_pred)))


from scipy.stats import pearsonr
pearsonr(y,y_pred)

In [6]:
import pandas as pd
devinfodf = pd.read_csv('/home/yt/cinevis/mediaeval/dev-set-info.csv')
testinfodf = pd.read_csv('/home/yt/cinevis/mediaeval/test-set-info.csv')

In [7]:
testinfodf


MOVIE   CAP_PROP_FRAME_WIDTH   CAP_PROP_FRAME_HEIGHT  \
0   MEDIAEVAL17_00.mp4                    640                     376   
1   MEDIAEVAL17_01.mp4                    640                     360   
2   MEDIAEVAL17_02.mp4                    624                     352   
3   MEDIAEVAL17_03.mp4                    640                     360   
4   MEDIAEVAL17_04.mp4                   1280                     720   
5   MEDIAEVAL17_05.mp4                    640                     360   
6   MEDIAEVAL17_06.mp4                    720                     400   
7   MEDIAEVAL17_07.mp4                    640                     360   
8   MEDIAEVAL17_08.mp4                    640                     360   
9   MEDIAEVAL17_09.mp4                    640                     360   
10  MEDIAEVAL17_10.mp4                    640                     360   
11  MEDIAEVAL17_11.mp4                    640                     360   
12  MEDIAEVAL17_12.mp4                    640                     360   
13  MEDIAEVAL17_13.mp4                    640                     360   

    CAP_PROP_POS_MSEC  CAP_PROP_POS_FRAMES  CAP_PROP_POS_AVI_RATIO  \
0                   0                    0                0.000042   
1                   0                    0                0.000040   
2                   0                    0                0.000083   
3                   0                    0                0.000033   
4                   0                    0                0.000033   
5                   0                    0                0.000040   
6                   0                    0                0.000078   
7                   0                    0                0.001000   
8                   0                    0                0.001000   
9                   0                    0                0.001000   
10                  0                    0                0.001000   
11                  0                    0                0.001000   
12                  0                    0                0.001000   
13                  0                    0                0.001000   

    CAP_PROP_FRAME_COUNT  CAP_PROP_FPS  CAP_PROP_FOURCC  CAP_PROP_FORMAT  \
0                  84348       23.9760      828602000.0                0   
1                  21118       25.0000      828602000.0                0   
2                 113253       23.9760      828602000.0                0   
3                 163719       29.9686      828602000.0                0   
4                  22887       29.9700      828602000.0                0   
5                 156520       25.0000      828602000.0                0   
6                 139841       25.0000      828602000.0                0   
7                   6298       29.9678      828602000.0                0   
8                   6292       29.9699      828602000.0                0   
9                   6298       29.9678      828602000.0                0   
10                  6298       29.9678      828602000.0                0   
11                  6298       29.9678      828602000.0                0   
12                  5039       23.9762      828602000.0                0   
13                  6298       29.9699      828602000.0                0   

    CAP_PROP_MODE  
0               0  
1               0  
2               0  
3               0  
4               0  
5               0  
6               0  
7               0  
8               0  
9               0  
10              0  
11              0  
12              0  
13              0

In [ ]:
%%time
rows = []
for ii in range(len(movgroups)):
    trainlist, testlist=gettraintestmovielist(ii)  # index 1 olanları test , diğerlerini train yapan fonksiyon
    tXv,tXa,tXd,ty = getFeatureswAnnotationsDf(trainlist)
    print(tXv.shape,tXa.shape,tXd.shape,ty.shape)
    testXv, testXa, testXd, testy = getFeatureswAnnotationsDf(testlist)
    print(testXv.shape, testXa.shape,testXd.shape, testy.shape)
    X_train, X_test, y_train, y_test     = train_test_split(tXv, ty,test_size=0.2, random_state=0)
    Xa_train, Xa_test, ya_train, ya_test = train_test_split(tXa, ty,test_size=0.2, random_state=0)
    Xd_train, Xd_test, yd_train, yd_test = train_test_split(tXd, ty,test_size=0.2, random_state=0)

    #X_train, X_test, y_train, y_test 
    y_pred_visV_train,mse,prs = evaluate_pipe(pipe_visual_valence, 
                                       X_train,y_train[['MeanValence']], 
                                       X_test,  y_test[['MeanValence']])
    #y_pred_vis,mse,prs = evaluate_pipe(pipe_visual_valence,tXv,ytrain,testXv,ytest)
    rows.append([ii,mse,prs[0]])
    y_pred_visV_test,mse,prs = evaluate_pipe(pipe_visual_valence, 
                                       tXv,ty[['MeanValence']], 
                                       testXv, testy[['MeanValence']])
    rows.append([ii,mse,prs[0]])
pipe_visual_valence_scores = pd.DataFrame(rows,columns=['test-group','MSE','PCC'])


In [8]:
movgroups = {
    0:['You_Again','Damaged_Kung_Fu','The_secret_number','Spaceman'],
    1:['Cloudland','Origami','Riding_The_Rails','Tears_of_Steel','Sintel'],
    2:['On_time','Elephant_s_Dream','Norm','Big_Buck_Bunny','Chatter','Full_Service'],
    3:['Islands','To_Claire_From_Sonny','Nuclear_Family','After_The_Rain','Parafundit'],
    4:['The_room_of_franz_kafka','Attitude_Matters','Lesson_Learned','Superhero'],
    5:['First_Bite','Wanted','Between_Viewings','Barely_legal_stories','Payload'],
    6:['Decay']
}


In [16]:
import os
os.system("mkdir fold"+str(2)+"/test/")

0

In [3]:
numcols = [str(i) for i in range(128)]

In [2]:
numcols

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126']

In [4]:
cols = ["noface","top", "left", "bottom", "right", "hframe", "wframe"]


In [5]:
cols + numcols

['noface',
 'top',
 'left',
 'bottom',
 'right',
 'hframe',
 'wframe',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127']

In [6]:
[1,2,3,4,5] + [1,2,3,4,5]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
numcols = [str(i) for i in range(128)]


In [13]:
len(numcols)

128

In [14]:
strx = "/home/yt/Desktop/cvpr2014/repro/mediaeval/data/dataset/movframes/Chatter.mp4-00001.jpg"

In [16]:
strx.split('/')[-1]

'Chatter.mp4-00001.jpg'

In [6]:
zerocols = [0.0 for i in range(144)]

In [7]:
map(lambda x: print x ,zerocols)


SyntaxError: invalid syntax (<ipython-input-7-b5c8abbd0874>, line 1)

In [34]:
kafkaroom = open("/tmp/kafkaroom.txt",'w')
landstr=''

for i in range(251):
    f = str(i) +' 720 1280 0 0.0 0.0 0.0 0.0'
    l = ''.join(" 0.0" for i in range(144) )
    landstr = landstr + f+l+'\n'
    kafkaroom.write(f+l+'\n')


In [35]:
print landstr

0 720 1280 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
1 720 1280 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

In [37]:
!wc -l /tmp/kafkaroom.txt

251 /tmp/kafkaroom.txt


In [48]:
import numpy as np
import pandas as pd

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.random.randint(1,10,(1,10))

array([[8, 9, 4, 5, 8, 9, 9, 7, 4, 6]])

In [94]:
np.empty(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [102]:
np.empty(10).reshape(-1,1)

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [92]:
r = np.random.randint(1,10,(1,200))
df=pd.DataFrame(r.transpose())
N=10
K=3
M = N + K     #Number of samples per row (sample + target) #indexes
            
sliding_window=1

In [89]:
A = np.array(df)[:,None,:]
A.shape
A.shape[0] - M + 1
np.arange(A.shape[0] - M + 1)
np.arange(A.shape[0] - M + 1).reshape(-1, 1)
np.arange(M)
np.arange(M) + np.arange(A.shape[0] - M + 1).reshape(-1, 1)


array([[  0,   1,   2, ...,  10,  11,  12],
       [  1,   2,   3, ...,  11,  12,  13],
       [  2,   3,   4, ...,  12,  13,  14],
       ..., 
       [185, 186, 187, ..., 195, 196, 197],
       [186, 187, 188, ..., 196, 197, 198],
       [187, 188, 189, ..., 197, 198, 199]])

In [76]:
if sliding_window:
    I = np.arange(M) + np.arange(A.shape[0] - M + 1).reshape(-1, 1)
else:
    if A.shape[0]%M == 0:
        I = np.arange(M)+np.arange(0,A.shape[0],M).reshape(-1,1)        
    else:
        I = np.arange(M)+np.arange(0,A.shape[0] -M,M).reshape(-1,1)


In [103]:
I[2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
B = A[I].reshape(-1, M * A.shape[1], A.shape[2])
ci = N * A.shape[1]    #Number of features per sample
B[:, :ci], B[:, ci:] #Sample matrix, Target matrix


(array([[[7],
         [6],
         [8],
         ..., 
         [2],
         [4],
         [2]],
 
        [[6],
         [8],
         [8],
         ..., 
         [4],
         [2],
         [7]],
 
        [[8],
         [8],
         [2],
         ..., 
         [2],
         [7],
         [1]],
 
        ..., 
        [[3],
         [1],
         [1],
         ..., 
         [3],
         [1],
         [5]],
 
        [[1],
         [1],
         [9],
         ..., 
         [1],
         [5],
         [9]],
 
        [[1],
         [9],
         [6],
         ..., 
         [5],
         [9],
         [1]]]), array([[[7],
         [1],
         [2]],
 
        [[1],
         [2],
         [1]],
 
        [[2],
         [1],
         [2]],
 
        [[1],
         [2],
         [4]],
 
        [[2],
         [4],
         [7]],
 
        [[4],
         [7],
         [1]],
 
        [[7],
         [1],
         [7]],
 
        [[1],
         [7],
         [2]],
 
        [[7],
 

In [105]:
ci

10

In [32]:
def getno(word):
    for i in word:
        no = ord(i) - ord('0')
        if (no > 0 and no < 10):
            return no
    return -1
            
def order(sentence):
  # code here
    if len(sentence):
        l = sentence.split()
        wdict = {}
        for word in l:
            no = getno(word)
            wdict[getno(word)] = word
      
        out = ""
        for i in range(1,len(l)+1):
            out = out +" "+ wdict[i]
      
        return out.strip()     
    else:
        return ""
    return ""

In [33]:
order("is2 Thi1s T4est 3a")

'Thi1s is2 3a T4est'

In [21]:
s = "is2 Thi1s T4est 3a"

In [12]:
l=s.split()

In [51]:
sorted([sorted(w) for w in l])

[['1', 'T', 'h', 'i', 's'],
 ['2', 'i', 's'],
 ['3', 'a'],
 ['4', 'T', 'e', 's', 't']]

In [13]:
for i in l[0]:
    print (ord('9') - ord(i),i) 

(-48, 'i')
(-58, 's')
(7, '2')


In [36]:
getno('is2')

2

In [34]:
def order(sentence):
    return " ".join(sorted(sentence.split(), key=lambda x: int(filter(str.isdigit, x))))

In [35]:
order("is2 Thi1s T4est 3a")

'Thi1s is2 3a T4est'

In [42]:
sorted(s.split(),key=lambda x: int(filter(str.isdigit,x)))

['Thi1s', 'is2', '3a', 'T4est']

In [41]:
map(lambda x:int(filter(str.isdigit,x)),l)

[2, 1, 4, 3]

In [45]:
def order2(words):
  return ' '.join(sorted(words.split(), key=lambda w:sorted(w)))

In [46]:
order2("is2 Thi1s T4est 3a")

'Thi1s is2 3a T4est'